# Generated by Django 4.2 on 2023-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourspower', models.CharField(max_length=200)),
                ('massa', models.CharField(max_length=200)),
                ('spudi', models.CharField(max_length=200)),
            ],
        ),
    ]
